# Generated by Django 3.0.1 on 2020-02-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamresult',
            name='time_taken',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
