# Generated by Django 3.0.1 on 2020-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_app', '0002_studentexamresult_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamresult',
            name='time_taken',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentexamstatus',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
